### ISSUE TITLE
manga-py pillow error

### ISSUE THREAD

**Issue by bumbaras** [manga-py/manga-py#440]
After manga-py --debug-version i get:
Traceback (most recent call last):                                                                                                         
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\manga_py\cli\_args_debug.py", line 13, in package_version
    pkg = __import__(name)
                     -> 'Pillow~=8.1'
ModuleNotFoundError: No module named 'Pillow~=8'

Pillow 9.0.1 is installed.

EDIT: ok, i just reinstalled pillow to version 8.x. But is manga-py really not compatible with pillow 9.x or it is only rusty fragment of checkup?

**Comment by 1271** [comment]
Do not install python modules in global packages.

Try using venv:

```bash
python -m venv venv
```

Then (in windows example):

```
venv\Scripts\activate
```

You are now inside venv and can install whatever packages you need.

Using the global environment deprives you of this ability.

**Comment by 1271** [comment]
That is, you can use several versions of packages at the same time, for example.

manga-py uses exactly version 8 of pillow, because In version 9, the necessary functionality was scrapped. I don’t remember what exactly, but so far I don’t plan to change it somehow. At least as long as pillow8 supports up-to-date versions of python

Perhaps this will change in the future

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
